source 'https://rubygems.org'

gem 'rake'
gem 'sqlite3'
gem 'marc'
gem 'rest-client'
gem 'nokogiri'
gem 'colorize'
gem 'selenium-webdriver'
gem 'activerecord'
gem 'minitest'
gem 'minitest-focus'
gem 'pry'
gem 'database_cleaner'
